---
title: "R Notebook"
output: html_notebook
---

```{r}

#Instalamos las librerías necesarias

install.packages("tidyverse") 
install.packages("readxl") 
install.packages("conflicted")

```

```{r}

#Cargamos las librerias

library(tidyverse)
library(readxl)
library(conflicted)
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("lag", "dplyr")

```

```{r}

#Cargamos los archivos, primera aproximación a los datos

df_vcc <- read_xlsx("dataset_vcc_2024.02.xlsx")
df_biopsias <- read_xlsx("dataset_biopsias_2024.02.xlsx")
View(df_vcc)
View(df_biopsias)
head(df_vcc)
head(df_biopsias)
summary(df_vcc)
summary(df_biopsias)

```

```{r}

#Evaluamos los NA por columna en el df_vcc

nas_por_columna <- colSums(is.na(df_vcc))
print(nas_por_columna)

```

```{r}

#Evaluamos los NA por columna en el df_biopsias

nas_por_columna <- colSums(is.na(df_biopsias))
print(nas_por_columna)

```

```{r}

#Armamos una columna en el df_vcc que indique si la preparacion del paciente fue adecuada o no.
#El criterio para considerar que la preparacion del paciente si es adecuada se toma de la bibliografia
#Fuente: https://bancos.salud.gob.ar/sites/default/files/2020-10/2020-10-27-indicadores-calidad-para-vcc-en-tamizaje-ccr.pdf

preparacion_segun_boston <- function(Colon_izquierdo, Colon_transverso, Colon_derecho, Escala_de_Boston) {
  if (Escala_de_Boston >= 6 & Colon_izquierdo >=2 & Colon_transverso >=2 & Colon_derecho >=2) {
    return("SI")
  }
  else {
    return("NO")
  }
}
  
df_vcc <- df_vcc %>%
  mutate(Preparacion_adecuada = mapply(preparacion_segun_boston, Colon_izquierdo, Colon_transverso, Colon_derecho, Escala_de_Boston))

View(df_vcc)

```

```{r}

#Unimos los dataset df_vcc y df_biopsias de acuerdo a la columna ID_laboratorio. Nos interesan los datos de las columnas "Histologia" y "Patologo"

df_vcc2 <- df_vcc
df_vcc_biopsias <- merge(df_vcc, df_biopsias[, c("ID_laboratorio", "Histologia", "Patologo")], by = "ID_laboratorio", all = TRUE)
df_vcc2 <- df_vcc_biopsias
View(df_vcc2)

```

```{r}

#Vemos que hay filas NA en el df resultante, las contabilizamos y decidimos filtrarlas (ya que se trata de biopsias que no se han extraido de las endoscopias que nos interesa analizar, es decir, no surgen de las videocolonoscopias realizadas en febrero de los centros médicos bajo estudio)

total_nas <- sum(is.na(df_vcc2$ID_paciente))
print(total_nas)
df_vcc2 <- df_vcc2 %>%
  filter(!is.na(ID_paciente))
View(df_vcc2)

```

```{r}

#Indicamos "No encontrado" en las columnas "Histologia" y "Patologo"

df_vcc2$Histologia <- ifelse(is.na(df_vcc2$Histologia), "No encontrado", df_vcc2$Histologia)
df_vcc2$Patologo <- ifelse(is.na(df_vcc2$Patologo), "No encontrado", df_vcc2$Patologo)
View(df_vcc2)

```

```{r}

#Revisamos si hay pacientes duplicados

hay_duplicados <- any(duplicated(df_vcc2$ID_paciente))
valores_duplicados <- df_vcc2$ID_paciente[duplicated(df_vcc2$ID_paciente)]
print(hay_duplicados)
print(valores_duplicados)

```

```{r}

#Miramos en detalle los pacientes duplicados

ver_duplicados <- filter(df_vcc2, df_vcc2$ID_paciente == "139356" | df_vcc2$ID_paciente == "585659" | df_vcc2$ID_paciente == "589942" |df_vcc2$ID_paciente == "591555" |df_vcc2$ID_paciente == "578373" |df_vcc2$ID_paciente == "592604" |df_vcc2$ID_paciente == "16425" |df_vcc2$ID_paciente == "591536")
ver_duplicados

```

```{r}

#En el chunk anterior comprobamos que en la mayoría de los casos en donde se repiten los ID_paciente es porque efectivamente se trata del mismo paciente pero que realizó dos endoscopías distintas en el mismo mes, o con dos operadores médicos diferentes, por lo cual no es un error del dataframe, sino que es información consistente. Sin embargo, detectamos un único caso de un paciente en donde coinciden todos los campos excepto el equipo utilizado, ese registro lo vamos a eliminar porque se trata de un error humano al momento de ingresar la información

df_vcc2 <- filter(df_vcc2, !(ID_paciente == "585659" & Equipo == "O8 - OLYMPUS CF-H170L"))
View(df_vcc2)

```

```{r}

#Una vez hecha la preparación y primera aproximación a los datos, nos abocamos al analisis mensual de los indicadores solicitados por la Gerencia. Primero, un ranking de los 10 operadores médicos que más procedimientos endoscópicos realizaron.

top10_operadores <- df_vcc2 %>%
  group_by(Medico_operador) %>%
  summarise(Frecuencia = n()) %>%
  arrange(desc(Frecuencia)) %>%
  head(10)
View(top10_operadores)

```

```{r}

# En segundo lugar, calculamos la Tasa de Intubacion Cecal (TIC), es decir, la proporción de llegada a ciego. La bibliografia indica que el mínimo estándar es >=90% y el objetivo estándar es >=95%. 
#Fuente: https://bancos.salud.gob.ar/sites/default/files/2020-10/2020-10-27-indicadores-calidad-para-vcc-en-tamizaje-ccr.pdf 
#Analizamos cuáles son los 10 operadores médicos que alcanzaron la mejor TIC.

TIC_boolean <- function(Llegada_a_ciego) {
  if (Llegada_a_ciego == "SI") {
    return(1)
  }
  else {
    return(0)
  }
}
  
df_vcc2 <- df_vcc2 %>%
  mutate(Llegada_a_ciego_boolean = mapply(TIC_boolean, Llegada_a_ciego))

top10_tic <- df_vcc2 %>%
  group_by(Medico_operador) %>%
  summarise(
    Total_procedimientos = n(),
    TIC = round(sum(Llegada_a_ciego_boolean) / n() * 100,2)) %>%
  arrange(desc(TIC)) %>%
  head(10)

View(top10_tic)

#El siguiente bloque de código lo usé para corroborar que la TIC sea correcta
#df_tic_por_operador <- aggregate(Llegada_a_ciego_boolean ~ Medico_operador, data = df_vcc2, FUN = sum)
#View(df_tic_por_operador)

```

```{r}

#También necesitamos conocer cuáles son los operadores médicos que este mes no alcanzaron los objetivos de calidad propuestos

df_tic_no_alcanza <- df_vcc2 %>%
  group_by(Medico_operador) %>%
  summarise(
    Total_procedimientos = n(),
    TIC = round(sum(Llegada_a_ciego_boolean) / n() * 100,2)) %>%
  filter(TIC<90) %>%
  arrange(desc(TIC))

View(df_tic_no_alcanza)

```

```{r}

#Evaluamos cuáles centros de salud han realizado más procedimientos. Nos interesan los 5 primeros centros, y el resto los agrupamos en la categoría "Otros_centros"

df_centros <- df_vcc2 %>%
  group_by(Centro) %>%
  summarise(Frecuencia = n()) %>%
  arrange(desc(Frecuencia))

top5_centros <- df_centros %>% head(5)

df_centros <- df_centros %>%
  mutate(Centros = ifelse(Centro %in% top5_centros$Centro, as.character(Centro), "Otros_centros"))

df_centros <- df_centros %>%
  group_by(Centros) %>%
  summarise(Total_procedimientos = sum(Frecuencia)) %>%
  arrange(desc(Total_procedimientos))

View(df_centros)

# Convertimos 'Centros' en un factor ordenado para que el gráfico quede en orden de frecuencia

df_centros$Centros <- factor(df_centros$Centros, levels = df_centros$Centros[order(df_centros$Total_procedimientos, decreasing = TRUE)])

# Queremos que el gráfico muestre los porcentajes en vez de las frecuencias absolutas

df_centros <- df_centros %>%
  mutate(Porcentaje = round(Total_procedimientos / sum(Total_procedimientos) * 100,2))

# Graficamos

g1 <- ggplot(df_centros)
g1 <- g1 + aes(x = "", y = Total_procedimientos, fill = Centros)
g1 <- g1 + geom_bar(stat = "identity", width = 1)
g1 <- g1 + geom_text(aes(label = paste0(round(Porcentaje, 1), "%")), position = position_stack(vjust = 0.5))
g1 <- g1 + scale_fill_manual(values = c("pink", "lightblue", "yellow", "lightgreen", "grey", "violet"))
g1 <- g1 + xlab(NULL)
g1 <- g1 + ylab("Cantidad de procedimientos")
g1 <- g1 + ggtitle("Top 5 Centros en cantidad de procedimientos", subtitle = "Febrero 2024")
g1 <- g1 + coord_polar("y")
g1 <- g1 + theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
print(g1)

```

```{r}

#Analizamos el resultado de biopsias (columna Histologia) según sexo biológico. Descartamos para el análisis los casos donde el patólogo aún no envió los resultados.

grafico_histologia <- filter(df_vcc2, !(Histologia == "No encontrado"))
grafico_histologia <- aggregate(grafico_histologia$Sexo_biologico, by = list (grafico_histologia$Sexo_biologico,grafico_histologia$Histologia), FUN=length)
colnames(grafico_histologia) <- c("Sexo_biologico", "Resultado_biopsia", "Cantidad")
View(grafico_histologia)

g2 <- ggplot(grafico_histologia) 
g2 <- g2 + aes (x =  Resultado_biopsia, y = Cantidad, fill = Sexo_biologico)
g2 <- g2 + geom_bar(stat = "identity", position = "dodge", width = 0.75)
g2 <- g2 + geom_text(aes(label = Cantidad), vjust = -0.1, position = position_dodge(width = 0.75))
g2 <- g2 + scale_fill_manual (values = c("pink","lightblue", "yellow"))
g2 <- g2 + xlab ("Resultados Biopsias")
g2 <- g2 + ylab ("Cantidad")
g2 <- g2 + ggtitle ("Resultados de biopsias según sexo biológico", subtitle = "Febrero 2024")
g2 <- g2 + theme(axis.text.x = element_text(angle = 25, hjust = 0.9))
g2

```

```{r}

# Por el gráfico anterior, decidimos detenernos en analizar la proporción de hombres y mujeres en los que se halló algún tipo de polipo considerando los totales por sexo biológico. Si bien a primera vista parecen porcentajes similares, cuando hacemos esto vemos que se hay una mayor tasa de hallazgo de pólipos en pacientes masculinos: se encontraron pólipos en el 34% de las mujeres y en el 45.5% de los hombres. 

polipos_por_sexo <- filter(df_vcc2, !(Sexo_biologico == "No informa")) %>%
  group_by(Sexo_biologico, Hallazgo_de_polipos) %>%
  summarise(Cantidad = n()) %>%
  group_by(Sexo_biologico) %>%
  mutate(Porcentaje = round((Cantidad / sum(Cantidad)) * 100, 2)) %>%
  arrange(Sexo_biologico, Hallazgo_de_polipos)

View(polipos_por_sexo)

# También analizamos en qué proporción de hombres y mujeres se hallaron adenomas, y encontramos que el porcentaje es levemente mayor en pacientes masculinos (9.14% de adenomas hallados en mujeres, 13.04% de adenomas hallados en hombres) 

adenomas_por_sexo <- filter(df_vcc2, !(Sexo_biologico == "No informa")) %>%
  mutate(Hay_adenoma = ifelse(Histologia %in% c("Adenocarcinoma", "Adenoma tubular", "Adenoma tubulovelloso", "Adenoma velloso", "Adenoma serrado", "Hiperplasico", "Otros"), "SI", "NO")) %>%
  group_by(Sexo_biologico, Hay_adenoma) %>%
  summarise(Total = n()) %>%
  arrange(Sexo_biologico, Hay_adenoma) %>%
  group_by(Sexo_biologico) %>%
  mutate(Porcentaje = round((Total / sum(Total)) * 100,2)) %>%
  select(-Total)

View(adenomas_por_sexo)

```

```{r}

#Evaluamos mediante regresión linear la relación entre edad y cantidad de pólipos hallados. Concentramos el análisis en los casos en donde se hallaron 3 o más pólipos. No se evidencia una relación entre edad de los pacientes y cantidad de pólipos hallados.

df_filtered <- df_vcc2[!(df_vcc2$Cantidad_de_polipos %in% c(0, 1, 2)), ]

edad_polipos <- lm (Cantidad_de_polipos ~ Edad_paciente, data=df_filtered)
plot (Cantidad_de_polipos ~ Edad_paciente, data=df_filtered,
xlab = "Edad", ylab = "Cant. Pólipos",
main = "Cantidad de pólipos hallados vs edad del paciente")
pairs(Cantidad_de_polipos ~ Edad_paciente, data = df_filtered)
abline (edad_polipos, col = "red")
summary(edad_polipos)

```




